name:CI pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on:ubuntu-latest
    
    steps:
      - name:Get Repo Access
        uses:actions/checkout@v4
      
      - name:Install node js
        uses:actions/setup-node@v4
        with:
          node-version:22 

      - name:Install Dependencies
        run:npm install